spring.application.name=saibaba

# ✅ TiDB Cloud Database
spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12820775
spring.datasource.username=sql12820775
spring.datasource.password=nWpr1SCcs2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sanathmandala391@gmail.com
spring.mail.password=xoydoqrhnsrcjzzu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server port for Render
server.port=${PORT:8080}

# Cashfree
cashfree.app.id=121304495b973d7ae8b4bba33214403121
cashfree.secret.key=cfsk_ma_prod_de7ed576db7a149176b874e015f30432_a6af54ef
cashfree.base.url=https://api.cashfree.com/pg
app.frontend.url=https://frontend-serve-ease-mtnc.vercel.app
app.backend.url=https://servicesproject-2.onrender.com
